import React from 'react';
import Icon from '../../../components/AppIcon';

const DisclaimerSection = ({ ...props }) => {
  return (
    <div className="bg-warning/5 border border-warning/20 rounded-xl p-6 lg:p-8" {...props}>
      <div className="flex items-start gap-4">
        <div className="flex-shrink-0">
          <div className="flex items-center justify-center w-12 h-12 bg-warning/10 rounded-lg">
            <Icon name="AlertTriangle" size={24} color="var(--color-warning)" />
          </div>
        </div>
        <div className="flex-1">
          <h3 className="text-lg lg:text-xl font-heading font-semibold text-foreground mb-3">
            Important Legal Disclaimer
          </h3>
          <div className="space-y-3 text-sm lg:text-base text-muted-foreground">
            <p>
              The legal action plan generated by this tool is for informational and educational purposes only. It does not constitute legal advice and should not be relied upon as a substitute for consultation with a qualified legal professional.
            </p>
            <ul className="space-y-2 ml-4">
              <li className="flex items-start gap-2">
                <Icon name="Dot" size={16} color="var(--color-warning)" className="flex-shrink-0 mt-1" />
                <span>Every legal situation is unique and may require specialized expertise</span>
              </li>
              <li className="flex items-start gap-2">
                <Icon name="Dot" size={16} color="var(--color-warning)" className="flex-shrink-0 mt-1" />
                <span>Laws and procedures vary by jurisdiction and are subject to change</span>
              </li>
              <li className="flex items-start gap-2">
                <Icon name="Dot" size={16} color="var(--color-warning)" className="flex-shrink-0 mt-1" />
                <span>Time limits and deadlines are critical in legal matters - consult a lawyer immediately</span>
              </li>
              <li className="flex items-start gap-2">
                <Icon name="Dot" size={16} color="var(--color-warning)" className="flex-shrink-0 mt-1" />
                <span>This tool cannot account for all facts and circumstances of your specific case</span>
              </li>
            </ul>
            <p className="font-medium text-foreground">
              We strongly recommend consulting with a licensed attorney before taking any legal action based on this guidance.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerSection;